apiVersion: v1
kind: Service
metadata:
  name: emibank-api
spec:
  type: NodePort
  selector:
    app: emibank-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
