apiVersion: apps/v1
kind: Deployment
metadata:
  name: emibank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emibank-api
  template:
    metadata:
      labels:
        app: emibank-api
    spec:
      containers:
        - name: emibank-api
          image: kristijanhaubrichoptiva/emibank:emibank_v.1.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://emibank-db:5432/emibank_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres