apiVersion: apps/v1
kind: Deployment
metadata:
  name: emibank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emibank-api
  template:
    metadata:
      labels:
        app: emibank-api
    spec:
      containers:
        - name: emibank-api
          image: kristijanhaubrichoptiva/emibank:1.2
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: api-secret
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_USERNAME
                  name: api-secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATASOURCE_PASSWORD
                  name: api-secret