apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vZW1pYmFuay1kYjo1NDMyL2VtaWJhbmtfZGI=
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=
immutable: true