apiVersion: apps/v1
kind: Deployment
metadata:
  name: emibank-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emibank-db
  template:
    metadata:
      labels:
        app: emibank-db
    spec:
      containers:
        - name: emibank-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: emibank_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres